excluded:
  - .build

opt_in_rules:
  - attributes
  - closure_spacing
  - conditional_returns_on_newline
  - empty_count
  - first_where
  - operator_usage_whitespace
  - sorted_imports

disabled_rules:
  - inclusive_language

identifier_name:
  excluded:

line_length:
  ignores_urls: true
